version: '3.8'

services:
  postgres:
    container_name: walletbackend-postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: walletdb
    ports:
      - "5440:5432"
    networks:
      - wallet-network

networks:
  wallet-network:
    driver: bridge
